/********************************************************************************
** Form generated from reading UI file 'EnterWindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.12
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_ENTERWINDOW_H
#define UI_ENTERWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QGraphicsView>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QWidget>
#include "animatedgraphicsview.h"

QT_BEGIN_NAMESPACE

class Ui_EnterWindowClass
{
public:
    QWidget *MainWidget;
    QGraphicsView *productorUI;
    QGraphicsView *gameTittle;
    QGraphicsView *mainEnterUI;
    QGraphicsView *gameTipBox;
    AnimatedGraphicsView *newJounary_Gra;
    AnimatedGraphicsView *loadGame_Gra;
    AnimatedGraphicsView *exitGame_Gra;
    QGraphicsView *LoadUI;
    AnimatedGraphicsView *LoadSlot_1;
    AnimatedGraphicsView *LoadSlot_2;
    AnimatedGraphicsView *LoadSlot_3;
    QLabel *LoadSlot_1_Label_1;
    QLabel *LoadSlot_2_Label_1;
    QLabel *LoadSlot_3_Label_1;
    QLabel *LoadSlot_1_Label_2;
    QLabel *LoadSlot_1_Label_3;
    QLabel *LoadSlot_1_Label_4;
    QLabel *LoadSlot_1_Label_5;
    QLabel *LoadSlot_1_Label_6;
    QLabel *LoadSlot_2_Label_2;
    QLabel *LoadSlot_2_Label_3;
    QLabel *LoadSlot_2_Label_4;
    QLabel *LoadSlot_2_Label_5;
    QLabel *LoadSlot_2_Label_6;
    QLabel *LoadSlot_3_Label_2;
    QLabel *LoadSlot_3_Label_3;
    QLabel *LoadSlot_3_Label_4;
    QLabel *LoadSlot_3_Label_5;
    QLabel *LoadSlot_3_Label_6;
    QGraphicsView *CustomizeUI;
    QGraphicsView *PropertyGra_customizeSlot_1;
    QGraphicsView *PropertyGra_customizeSlot_2;
    QGraphicsView *PropertyGra_customizeSlot_3;
    QLabel *SkillPoint_TextLabel;
    AnimatedGraphicsView *Bullet_CustomizeSlot_1;
    AnimatedGraphicsView *Bullet_CustomizeSlot_2;
    AnimatedGraphicsView *Bullet_CustomizeSlot_3;
    AnimatedGraphicsView *Bullet_CustomizeSlot_4;
    AnimatedGraphicsView *Bullet_CustomizeSlot_5;
    QPushButton *CustomizeOver_Button;
    QPushButton *Increase_button_customizeSlot_3;
    QPushButton *Increase_button_customizeSlot_1;
    QPushButton *Increase_button_customizeSlot_2;
    QPushButton *Decrease_button_customizeSlot_1;
    QPushButton *Decrease_button_customizeSlot_2;
    QPushButton *Decrease_button_customizeSlot_3;
    QGraphicsView *SkillPoint_ATK_4;
    QGraphicsView *SkillPoint_ATK_9;
    QGraphicsView *SkillPoint_ATK_1;
    QGraphicsView *SkillPoint_ATK_6;
    QGraphicsView *SkillPoint_ATK_8;
    QGraphicsView *SkillPoint_ATK_5;
    QGraphicsView *SkillPoint_ATK_3;
    QGraphicsView *SkillPoint_ATK_10;
    QGraphicsView *SkillPoint_ATK_2;
    QGraphicsView *SkillPoint_ATK_7;
    QGraphicsView *SkillPoint_DEF_8;
    QGraphicsView *SkillPoint_DEF_9;
    QGraphicsView *SkillPoint_DEF_5;
    QGraphicsView *SkillPoint_DEF_10;
    QGraphicsView *SkillPoint_DEF_3;
    QGraphicsView *SkillPoint_DEF_1;
    QGraphicsView *SkillPoint_DEF_7;
    QGraphicsView *SkillPoint_DEF_6;
    QGraphicsView *SkillPoint_DEF_4;
    QGraphicsView *SkillPoint_DEF_2;
    QGraphicsView *SkillPoint_HP_8;
    QGraphicsView *SkillPoint_HP_3;
    QGraphicsView *SkillPoint_HP_6;
    QGraphicsView *SkillPoint_HP_10;
    QGraphicsView *SkillPoint_HP_4;
    QGraphicsView *SkillPoint_HP_5;
    QGraphicsView *SkillPoint_HP_2;
    QGraphicsView *SkillPoint_HP_7;
    QGraphicsView *SkillPoint_HP_1;
    QGraphicsView *SkillPoint_HP_9;
    QGraphicsView *SelectFrame_1;
    QGraphicsView *SelectFrame_2;
    QGraphicsView *SelectFrame_3;
    QGraphicsView *SelectFrame_4;
    QGraphicsView *SelectFrame_5;

    void setupUi(QMainWindow *EnterWindowClass)
    {
        if (EnterWindowClass->objectName().isEmpty())
            EnterWindowClass->setObjectName(QString::fromUtf8("EnterWindowClass"));
        EnterWindowClass->resize(960, 540);
        EnterWindowClass->setMinimumSize(QSize(0, 0));
        EnterWindowClass->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/EnterUI1.bmp);"));
        MainWidget = new QWidget(EnterWindowClass);
        MainWidget->setObjectName(QString::fromUtf8("MainWidget"));
        MainWidget->setStyleSheet(QString::fromUtf8(""));
        productorUI = new QGraphicsView(MainWidget);
        productorUI->setObjectName(QString::fromUtf8("productorUI"));
        productorUI->setGeometry(QRect(0, 0, 960, 540));
        productorUI->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/EnterUI1.bmp);"));
        gameTittle = new QGraphicsView(MainWidget);
        gameTittle->setObjectName(QString::fromUtf8("gameTittle"));
        gameTittle->setEnabled(true);
        gameTittle->setGeometry(QRect(331, 100, 300, 108));
        gameTittle->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/SuperBOX_Tittle_p.png); "));
        gameTittle->setSceneRect(QRectF(0, 0, 300, 108));
        mainEnterUI = new QGraphicsView(MainWidget);
        mainEnterUI->setObjectName(QString::fromUtf8("mainEnterUI"));
        mainEnterUI->setGeometry(QRect(0, 0, 960, 540));
        mainEnterUI->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/EnterBG1.png);"));
        gameTipBox = new QGraphicsView(MainWidget);
        gameTipBox->setObjectName(QString::fromUtf8("gameTipBox"));
        gameTipBox->setGeometry(QRect(0, 515, 960, 25));
        gameTipBox->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/TipBox.png);"));
        newJounary_Gra = new AnimatedGraphicsView(MainWidget);
        newJounary_Gra->setObjectName(QString::fromUtf8("newJounary_Gra"));
        newJounary_Gra->setGeometry(QRect(384, 240, 192, 32));
        newJounary_Gra->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/Button_NewGame.png);\n"
"\n"
""));
        loadGame_Gra = new AnimatedGraphicsView(MainWidget);
        loadGame_Gra->setObjectName(QString::fromUtf8("loadGame_Gra"));
        loadGame_Gra->setGeometry(QRect(416, 290, 128, 32));
        loadGame_Gra->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/Button_LoadGame.png);"));
        exitGame_Gra = new AnimatedGraphicsView(MainWidget);
        exitGame_Gra->setObjectName(QString::fromUtf8("exitGame_Gra"));
        exitGame_Gra->setGeometry(QRect(416, 340, 128, 32));
        exitGame_Gra->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BG/Button_Exit.png);"));
        LoadUI = new QGraphicsView(MainWidget);
        LoadUI->setObjectName(QString::fromUtf8("LoadUI"));
        LoadUI->setGeometry(QRect(200, 100, 560, 352));
        LoadUI->setStyleSheet(QString::fromUtf8("border-image: url(:/image/LoadSystem/LoadGame_BG.png);"));
        LoadSlot_1 = new AnimatedGraphicsView(MainWidget);
        LoadSlot_1->setObjectName(QString::fromUtf8("LoadSlot_1"));
        LoadSlot_1->setGeometry(QRect(360, 200, 240, 60));
        LoadSlot_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/LoadSystem/LoadUI_SLOT_Empty.jpg);"));
        LoadSlot_2 = new AnimatedGraphicsView(MainWidget);
        LoadSlot_2->setObjectName(QString::fromUtf8("LoadSlot_2"));
        LoadSlot_2->setGeometry(QRect(360, 270, 240, 60));
        LoadSlot_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/LoadSystem/LoadUI_SLOT_Empty.jpg);"));
        LoadSlot_3 = new AnimatedGraphicsView(MainWidget);
        LoadSlot_3->setObjectName(QString::fromUtf8("LoadSlot_3"));
        LoadSlot_3->setGeometry(QRect(360, 340, 240, 60));
        LoadSlot_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/LoadSystem/LoadUI_SLOT_Empty.jpg);"));
        LoadSlot_1_Label_1 = new QLabel(MainWidget);
        LoadSlot_1_Label_1->setObjectName(QString::fromUtf8("LoadSlot_1_Label_1"));
        LoadSlot_1_Label_1->setGeometry(QRect(366, 201, 32, 20));
        QSizePolicy sizePolicy(QSizePolicy::Preferred, QSizePolicy::Preferred);
        sizePolicy.setHorizontalStretch(0);
        sizePolicy.setVerticalStretch(0);
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_1->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_1->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_1->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_1->setMaximumSize(QSize(32, 20));
        QPalette palette;
        QBrush brush(QColor(242, 177, 145, 255));
        brush.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        QBrush brush1(QColor(120, 120, 120, 255));
        brush1.setStyle(Qt::SolidPattern);
        palette.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_1->setPalette(palette);
        QFont font;
        font.setFamily(QString::fromUtf8("OpenSymbol"));
        font.setPointSize(8);
        font.setBold(true);
        font.setItalic(false);
        font.setWeight(75);
        font.setStrikeOut(false);
        font.setKerning(true);
        font.setStyleStrategy(QFont::PreferDefault);
        LoadSlot_1_Label_1->setFont(font);
        LoadSlot_1_Label_1->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_1->setScaledContents(true);
        LoadSlot_1_Label_1->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_1->setWordWrap(true);
        LoadSlot_2_Label_1 = new QLabel(MainWidget);
        LoadSlot_2_Label_1->setObjectName(QString::fromUtf8("LoadSlot_2_Label_1"));
        LoadSlot_2_Label_1->setGeometry(QRect(366, 270, 32, 20));
        QPalette palette1;
        palette1.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette1.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_1->setPalette(palette1);
        QFont font1;
        font1.setFamily(QString::fromUtf8("OpenSymbol"));
        font1.setPointSize(8);
        LoadSlot_2_Label_1->setFont(font1);
        LoadSlot_2_Label_1->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_1 = new QLabel(MainWidget);
        LoadSlot_3_Label_1->setObjectName(QString::fromUtf8("LoadSlot_3_Label_1"));
        LoadSlot_3_Label_1->setGeometry(QRect(366, 340, 32, 20));
        QPalette palette2;
        palette2.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette2.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_1->setPalette(palette2);
        LoadSlot_3_Label_1->setFont(font1);
        LoadSlot_3_Label_1->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_2 = new QLabel(MainWidget);
        LoadSlot_1_Label_2->setObjectName(QString::fromUtf8("LoadSlot_1_Label_2"));
        LoadSlot_1_Label_2->setGeometry(QRect(402, 201, 32, 20));
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_2->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_2->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_2->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_2->setMaximumSize(QSize(32, 20));
        QPalette palette3;
        palette3.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette3.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_2->setPalette(palette3);
        LoadSlot_1_Label_2->setFont(font);
        LoadSlot_1_Label_2->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_2->setScaledContents(true);
        LoadSlot_1_Label_2->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_2->setWordWrap(true);
        LoadSlot_1_Label_3 = new QLabel(MainWidget);
        LoadSlot_1_Label_3->setObjectName(QString::fromUtf8("LoadSlot_1_Label_3"));
        LoadSlot_1_Label_3->setGeometry(QRect(439, 201, 32, 20));
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_3->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_3->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_3->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_3->setMaximumSize(QSize(32, 20));
        QPalette palette4;
        palette4.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette4.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_3->setPalette(palette4);
        LoadSlot_1_Label_3->setFont(font);
        LoadSlot_1_Label_3->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_3->setScaledContents(true);
        LoadSlot_1_Label_3->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_3->setWordWrap(true);
        LoadSlot_1_Label_4 = new QLabel(MainWidget);
        LoadSlot_1_Label_4->setObjectName(QString::fromUtf8("LoadSlot_1_Label_4"));
        LoadSlot_1_Label_4->setGeometry(QRect(488, 201, 32, 20));
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_4->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_4->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_4->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_4->setMaximumSize(QSize(32, 20));
        QPalette palette5;
        palette5.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette5.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_4->setPalette(palette5);
        LoadSlot_1_Label_4->setFont(font);
        LoadSlot_1_Label_4->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_4->setScaledContents(true);
        LoadSlot_1_Label_4->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_4->setWordWrap(true);
        LoadSlot_1_Label_5 = new QLabel(MainWidget);
        LoadSlot_1_Label_5->setObjectName(QString::fromUtf8("LoadSlot_1_Label_5"));
        LoadSlot_1_Label_5->setGeometry(QRect(529, 201, 32, 20));
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_5->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_5->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_5->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_5->setMaximumSize(QSize(32, 20));
        QPalette palette6;
        palette6.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette6.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_5->setPalette(palette6);
        LoadSlot_1_Label_5->setFont(font);
        LoadSlot_1_Label_5->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_5->setScaledContents(true);
        LoadSlot_1_Label_5->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_5->setWordWrap(true);
        LoadSlot_1_Label_6 = new QLabel(MainWidget);
        LoadSlot_1_Label_6->setObjectName(QString::fromUtf8("LoadSlot_1_Label_6"));
        LoadSlot_1_Label_6->setGeometry(QRect(566, 201, 32, 20));
        sizePolicy.setHeightForWidth(LoadSlot_1_Label_6->sizePolicy().hasHeightForWidth());
        LoadSlot_1_Label_6->setSizePolicy(sizePolicy);
        LoadSlot_1_Label_6->setMinimumSize(QSize(32, 20));
        LoadSlot_1_Label_6->setMaximumSize(QSize(32, 20));
        QPalette palette7;
        palette7.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette7.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_1_Label_6->setPalette(palette7);
        LoadSlot_1_Label_6->setFont(font);
        LoadSlot_1_Label_6->setStyleSheet(QString::fromUtf8(""));
        LoadSlot_1_Label_6->setScaledContents(true);
        LoadSlot_1_Label_6->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_1_Label_6->setWordWrap(true);
        LoadSlot_2_Label_2 = new QLabel(MainWidget);
        LoadSlot_2_Label_2->setObjectName(QString::fromUtf8("LoadSlot_2_Label_2"));
        LoadSlot_2_Label_2->setGeometry(QRect(402, 270, 32, 20));
        QPalette palette8;
        palette8.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette8.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_2->setPalette(palette8);
        LoadSlot_2_Label_2->setFont(font1);
        LoadSlot_2_Label_2->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_2_Label_3 = new QLabel(MainWidget);
        LoadSlot_2_Label_3->setObjectName(QString::fromUtf8("LoadSlot_2_Label_3"));
        LoadSlot_2_Label_3->setGeometry(QRect(439, 270, 32, 20));
        QPalette palette9;
        palette9.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette9.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_3->setPalette(palette9);
        LoadSlot_2_Label_3->setFont(font1);
        LoadSlot_2_Label_3->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_2_Label_4 = new QLabel(MainWidget);
        LoadSlot_2_Label_4->setObjectName(QString::fromUtf8("LoadSlot_2_Label_4"));
        LoadSlot_2_Label_4->setGeometry(QRect(488, 270, 32, 20));
        QPalette palette10;
        palette10.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette10.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_4->setPalette(palette10);
        LoadSlot_2_Label_4->setFont(font1);
        LoadSlot_2_Label_4->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_2_Label_5 = new QLabel(MainWidget);
        LoadSlot_2_Label_5->setObjectName(QString::fromUtf8("LoadSlot_2_Label_5"));
        LoadSlot_2_Label_5->setGeometry(QRect(529, 270, 32, 20));
        QPalette palette11;
        palette11.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette11.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_5->setPalette(palette11);
        LoadSlot_2_Label_5->setFont(font1);
        LoadSlot_2_Label_5->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_2_Label_6 = new QLabel(MainWidget);
        LoadSlot_2_Label_6->setObjectName(QString::fromUtf8("LoadSlot_2_Label_6"));
        LoadSlot_2_Label_6->setGeometry(QRect(566, 270, 32, 20));
        QPalette palette12;
        palette12.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette12.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_2_Label_6->setPalette(palette12);
        LoadSlot_2_Label_6->setFont(font1);
        LoadSlot_2_Label_6->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_2 = new QLabel(MainWidget);
        LoadSlot_3_Label_2->setObjectName(QString::fromUtf8("LoadSlot_3_Label_2"));
        LoadSlot_3_Label_2->setGeometry(QRect(402, 340, 32, 20));
        QPalette palette13;
        palette13.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette13.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_2->setPalette(palette13);
        LoadSlot_3_Label_2->setFont(font1);
        LoadSlot_3_Label_2->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_3 = new QLabel(MainWidget);
        LoadSlot_3_Label_3->setObjectName(QString::fromUtf8("LoadSlot_3_Label_3"));
        LoadSlot_3_Label_3->setGeometry(QRect(439, 340, 32, 20));
        QPalette palette14;
        palette14.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette14.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_3->setPalette(palette14);
        LoadSlot_3_Label_3->setFont(font1);
        LoadSlot_3_Label_3->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_4 = new QLabel(MainWidget);
        LoadSlot_3_Label_4->setObjectName(QString::fromUtf8("LoadSlot_3_Label_4"));
        LoadSlot_3_Label_4->setGeometry(QRect(488, 340, 32, 20));
        QPalette palette15;
        palette15.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette15.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_4->setPalette(palette15);
        LoadSlot_3_Label_4->setFont(font1);
        LoadSlot_3_Label_4->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_5 = new QLabel(MainWidget);
        LoadSlot_3_Label_5->setObjectName(QString::fromUtf8("LoadSlot_3_Label_5"));
        LoadSlot_3_Label_5->setGeometry(QRect(529, 340, 32, 20));
        QPalette palette16;
        palette16.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette16.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_5->setPalette(palette16);
        LoadSlot_3_Label_5->setFont(font1);
        LoadSlot_3_Label_5->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        LoadSlot_3_Label_6 = new QLabel(MainWidget);
        LoadSlot_3_Label_6->setObjectName(QString::fromUtf8("LoadSlot_3_Label_6"));
        LoadSlot_3_Label_6->setGeometry(QRect(566, 340, 32, 20));
        QPalette palette17;
        palette17.setBrush(QPalette::Active, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Inactive, QPalette::WindowText, brush);
        palette17.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        LoadSlot_3_Label_6->setPalette(palette17);
        LoadSlot_3_Label_6->setFont(font1);
        LoadSlot_3_Label_6->setAlignment(Qt::AlignBottom|Qt::AlignHCenter);
        CustomizeUI = new QGraphicsView(MainWidget);
        CustomizeUI->setObjectName(QString::fromUtf8("CustomizeUI"));
        CustomizeUI->setGeometry(QRect(200, 100, 560, 352));
        CustomizeUI->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/Customize_UI.bmp);"));
        PropertyGra_customizeSlot_1 = new QGraphicsView(MainWidget);
        PropertyGra_customizeSlot_1->setObjectName(QString::fromUtf8("PropertyGra_customizeSlot_1"));
        PropertyGra_customizeSlot_1->setGeometry(QRect(260, 180, 32, 32));
        PropertyGra_customizeSlot_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/Property_Attack.bmp);"));
        PropertyGra_customizeSlot_2 = new QGraphicsView(MainWidget);
        PropertyGra_customizeSlot_2->setObjectName(QString::fromUtf8("PropertyGra_customizeSlot_2"));
        PropertyGra_customizeSlot_2->setGeometry(QRect(260, 230, 32, 32));
        PropertyGra_customizeSlot_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/Property_Denfence.bmp);"));
        PropertyGra_customizeSlot_3 = new QGraphicsView(MainWidget);
        PropertyGra_customizeSlot_3->setObjectName(QString::fromUtf8("PropertyGra_customizeSlot_3"));
        PropertyGra_customizeSlot_3->setGeometry(QRect(260, 280, 32, 32));
        PropertyGra_customizeSlot_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/Property_HP.bmp);"));
        SkillPoint_TextLabel = new QLabel(MainWidget);
        SkillPoint_TextLabel->setObjectName(QString::fromUtf8("SkillPoint_TextLabel"));
        SkillPoint_TextLabel->setGeometry(QRect(362, 417, 54, 12));
        QPalette palette18;
        QBrush brush2(QColor(255, 255, 255, 255));
        brush2.setStyle(Qt::SolidPattern);
        palette18.setBrush(QPalette::Active, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Inactive, QPalette::WindowText, brush2);
        palette18.setBrush(QPalette::Disabled, QPalette::WindowText, brush1);
        SkillPoint_TextLabel->setPalette(palette18);
        QFont font2;
        font2.setFamily(QString::fromUtf8("Pixel Number"));
        font2.setPointSize(8);
        SkillPoint_TextLabel->setFont(font2);
        SkillPoint_TextLabel->setTextFormat(Qt::AutoText);
        SkillPoint_TextLabel->setAlignment(Qt::AlignCenter);
        Bullet_CustomizeSlot_1 = new AnimatedGraphicsView(MainWidget);
        Bullet_CustomizeSlot_1->setObjectName(QString::fromUtf8("Bullet_CustomizeSlot_1"));
        Bullet_CustomizeSlot_1->setGeometry(QRect(250, 330, 64, 64));
        Bullet_CustomizeSlot_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BulletSlot_Energy.bmp);"));
        Bullet_CustomizeSlot_2 = new AnimatedGraphicsView(MainWidget);
        Bullet_CustomizeSlot_2->setObjectName(QString::fromUtf8("Bullet_CustomizeSlot_2"));
        Bullet_CustomizeSlot_2->setGeometry(QRect(320, 330, 64, 64));
        Bullet_CustomizeSlot_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BulletSlot_Ice.bmp);"));
        Bullet_CustomizeSlot_3 = new AnimatedGraphicsView(MainWidget);
        Bullet_CustomizeSlot_3->setObjectName(QString::fromUtf8("Bullet_CustomizeSlot_3"));
        Bullet_CustomizeSlot_3->setGeometry(QRect(390, 330, 64, 64));
        Bullet_CustomizeSlot_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BulletSlot_Stone.bmp);"));
        Bullet_CustomizeSlot_4 = new AnimatedGraphicsView(MainWidget);
        Bullet_CustomizeSlot_4->setObjectName(QString::fromUtf8("Bullet_CustomizeSlot_4"));
        Bullet_CustomizeSlot_4->setGeometry(QRect(460, 330, 64, 64));
        Bullet_CustomizeSlot_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BulletSlot_Thunder.bmp);"));
        Bullet_CustomizeSlot_5 = new AnimatedGraphicsView(MainWidget);
        Bullet_CustomizeSlot_5->setObjectName(QString::fromUtf8("Bullet_CustomizeSlot_5"));
        Bullet_CustomizeSlot_5->setGeometry(QRect(530, 330, 64, 64));
        Bullet_CustomizeSlot_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/BulletSlot_Water.bmp);"));
        CustomizeOver_Button = new QPushButton(MainWidget);
        CustomizeOver_Button->setObjectName(QString::fromUtf8("CustomizeOver_Button"));
        CustomizeOver_Button->setGeometry(QRect(520, 410, 78, 26));
        CustomizeOver_Button->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Customize_OverButton.bmp);"));
        CustomizeOver_Button->setAutoDefault(false);
        Increase_button_customizeSlot_3 = new QPushButton(MainWidget);
        Increase_button_customizeSlot_3->setObjectName(QString::fromUtf8("Increase_button_customizeSlot_3"));
        Increase_button_customizeSlot_3->setGeometry(QRect(500, 279, 36, 36));
        Increase_button_customizeSlot_3->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Increase_Button.bmp);"));
        Increase_button_customizeSlot_1 = new QPushButton(MainWidget);
        Increase_button_customizeSlot_1->setObjectName(QString::fromUtf8("Increase_button_customizeSlot_1"));
        Increase_button_customizeSlot_1->setEnabled(true);
        Increase_button_customizeSlot_1->setGeometry(QRect(500, 179, 36, 36));
        Increase_button_customizeSlot_1->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Increase_Button.bmp);"));
        Increase_button_customizeSlot_2 = new QPushButton(MainWidget);
        Increase_button_customizeSlot_2->setObjectName(QString::fromUtf8("Increase_button_customizeSlot_2"));
        Increase_button_customizeSlot_2->setGeometry(QRect(500, 229, 36, 36));
        Increase_button_customizeSlot_2->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Increase_Button.bmp);"));
        Decrease_button_customizeSlot_1 = new QPushButton(MainWidget);
        Decrease_button_customizeSlot_1->setObjectName(QString::fromUtf8("Decrease_button_customizeSlot_1"));
        Decrease_button_customizeSlot_1->setEnabled(true);
        Decrease_button_customizeSlot_1->setGeometry(QRect(550, 179, 36, 36));
        Decrease_button_customizeSlot_1->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Decrease_Button.bmp);"));
        Decrease_button_customizeSlot_2 = new QPushButton(MainWidget);
        Decrease_button_customizeSlot_2->setObjectName(QString::fromUtf8("Decrease_button_customizeSlot_2"));
        Decrease_button_customizeSlot_2->setGeometry(QRect(550, 229, 36, 36));
        Decrease_button_customizeSlot_2->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Decrease_Button.bmp);"));
        Decrease_button_customizeSlot_3 = new QPushButton(MainWidget);
        Decrease_button_customizeSlot_3->setObjectName(QString::fromUtf8("Decrease_button_customizeSlot_3"));
        Decrease_button_customizeSlot_3->setGeometry(QRect(550, 279, 36, 36));
        Decrease_button_customizeSlot_3->setStyleSheet(QString::fromUtf8("background-image: url(:/image/CustomizeUI/Decrease_Button.bmp);"));
        SkillPoint_ATK_4 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_4->setObjectName(QString::fromUtf8("SkillPoint_ATK_4"));
        SkillPoint_ATK_4->setGeometry(QRect(370, 180, 10, 32));
        QSizePolicy sizePolicy1(QSizePolicy::Ignored, QSizePolicy::Expanding);
        sizePolicy1.setHorizontalStretch(0);
        sizePolicy1.setVerticalStretch(0);
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_4->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_4->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_4->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_9 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_9->setObjectName(QString::fromUtf8("SkillPoint_ATK_9"));
        SkillPoint_ATK_9->setGeometry(QRect(445, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_9->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_9->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_9->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_9->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_1 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_1->setObjectName(QString::fromUtf8("SkillPoint_ATK_1"));
        SkillPoint_ATK_1->setGeometry(QRect(325, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_1->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_1->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_1->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_6 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_6->setObjectName(QString::fromUtf8("SkillPoint_ATK_6"));
        SkillPoint_ATK_6->setGeometry(QRect(400, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_6->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_6->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_6->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_6->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_8 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_8->setObjectName(QString::fromUtf8("SkillPoint_ATK_8"));
        SkillPoint_ATK_8->setGeometry(QRect(430, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_8->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_8->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_8->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_8->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_5 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_5->setObjectName(QString::fromUtf8("SkillPoint_ATK_5"));
        SkillPoint_ATK_5->setGeometry(QRect(385, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_5->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_5->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_5->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_3 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_3->setObjectName(QString::fromUtf8("SkillPoint_ATK_3"));
        SkillPoint_ATK_3->setGeometry(QRect(355, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_3->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_3->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_3->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_10 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_10->setObjectName(QString::fromUtf8("SkillPoint_ATK_10"));
        SkillPoint_ATK_10->setGeometry(QRect(460, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_10->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_10->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_10->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_10->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_2 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_2->setObjectName(QString::fromUtf8("SkillPoint_ATK_2"));
        SkillPoint_ATK_2->setGeometry(QRect(340, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_2->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_2->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_2->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_ATK_7 = new QGraphicsView(MainWidget);
        SkillPoint_ATK_7->setObjectName(QString::fromUtf8("SkillPoint_ATK_7"));
        SkillPoint_ATK_7->setGeometry(QRect(415, 180, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_ATK_7->sizePolicy().hasHeightForWidth());
        SkillPoint_ATK_7->setSizePolicy(sizePolicy1);
        SkillPoint_ATK_7->setMaximumSize(QSize(10, 32));
        SkillPoint_ATK_7->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot1.bmp);"));
        SkillPoint_DEF_8 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_8->setObjectName(QString::fromUtf8("SkillPoint_DEF_8"));
        SkillPoint_DEF_8->setGeometry(QRect(430, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_8->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_8->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_8->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_8->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_9 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_9->setObjectName(QString::fromUtf8("SkillPoint_DEF_9"));
        SkillPoint_DEF_9->setGeometry(QRect(445, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_9->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_9->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_9->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_9->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_5 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_5->setObjectName(QString::fromUtf8("SkillPoint_DEF_5"));
        SkillPoint_DEF_5->setGeometry(QRect(385, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_5->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_5->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_5->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_10 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_10->setObjectName(QString::fromUtf8("SkillPoint_DEF_10"));
        SkillPoint_DEF_10->setGeometry(QRect(460, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_10->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_10->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_10->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_10->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_3 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_3->setObjectName(QString::fromUtf8("SkillPoint_DEF_3"));
        SkillPoint_DEF_3->setGeometry(QRect(355, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_3->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_3->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_3->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_1 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_1->setObjectName(QString::fromUtf8("SkillPoint_DEF_1"));
        SkillPoint_DEF_1->setGeometry(QRect(325, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_1->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_1->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_1->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_7 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_7->setObjectName(QString::fromUtf8("SkillPoint_DEF_7"));
        SkillPoint_DEF_7->setGeometry(QRect(415, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_7->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_7->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_7->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_7->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_6 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_6->setObjectName(QString::fromUtf8("SkillPoint_DEF_6"));
        SkillPoint_DEF_6->setGeometry(QRect(400, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_6->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_6->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_6->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_6->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_4 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_4->setObjectName(QString::fromUtf8("SkillPoint_DEF_4"));
        SkillPoint_DEF_4->setGeometry(QRect(370, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_4->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_4->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_4->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_DEF_2 = new QGraphicsView(MainWidget);
        SkillPoint_DEF_2->setObjectName(QString::fromUtf8("SkillPoint_DEF_2"));
        SkillPoint_DEF_2->setGeometry(QRect(340, 230, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_DEF_2->sizePolicy().hasHeightForWidth());
        SkillPoint_DEF_2->setSizePolicy(sizePolicy1);
        SkillPoint_DEF_2->setMaximumSize(QSize(10, 32));
        SkillPoint_DEF_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot2.bmp);"));
        SkillPoint_HP_8 = new QGraphicsView(MainWidget);
        SkillPoint_HP_8->setObjectName(QString::fromUtf8("SkillPoint_HP_8"));
        SkillPoint_HP_8->setGeometry(QRect(430, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_8->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_8->setSizePolicy(sizePolicy1);
        SkillPoint_HP_8->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_8->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_3 = new QGraphicsView(MainWidget);
        SkillPoint_HP_3->setObjectName(QString::fromUtf8("SkillPoint_HP_3"));
        SkillPoint_HP_3->setGeometry(QRect(355, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_3->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_3->setSizePolicy(sizePolicy1);
        SkillPoint_HP_3->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_6 = new QGraphicsView(MainWidget);
        SkillPoint_HP_6->setObjectName(QString::fromUtf8("SkillPoint_HP_6"));
        SkillPoint_HP_6->setGeometry(QRect(400, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_6->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_6->setSizePolicy(sizePolicy1);
        SkillPoint_HP_6->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_6->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_10 = new QGraphicsView(MainWidget);
        SkillPoint_HP_10->setObjectName(QString::fromUtf8("SkillPoint_HP_10"));
        SkillPoint_HP_10->setGeometry(QRect(460, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_10->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_10->setSizePolicy(sizePolicy1);
        SkillPoint_HP_10->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_10->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_4 = new QGraphicsView(MainWidget);
        SkillPoint_HP_4->setObjectName(QString::fromUtf8("SkillPoint_HP_4"));
        SkillPoint_HP_4->setGeometry(QRect(370, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_4->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_4->setSizePolicy(sizePolicy1);
        SkillPoint_HP_4->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_5 = new QGraphicsView(MainWidget);
        SkillPoint_HP_5->setObjectName(QString::fromUtf8("SkillPoint_HP_5"));
        SkillPoint_HP_5->setGeometry(QRect(385, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_5->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_5->setSizePolicy(sizePolicy1);
        SkillPoint_HP_5->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_2 = new QGraphicsView(MainWidget);
        SkillPoint_HP_2->setObjectName(QString::fromUtf8("SkillPoint_HP_2"));
        SkillPoint_HP_2->setGeometry(QRect(340, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_2->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_2->setSizePolicy(sizePolicy1);
        SkillPoint_HP_2->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_7 = new QGraphicsView(MainWidget);
        SkillPoint_HP_7->setObjectName(QString::fromUtf8("SkillPoint_HP_7"));
        SkillPoint_HP_7->setGeometry(QRect(415, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_7->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_7->setSizePolicy(sizePolicy1);
        SkillPoint_HP_7->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_7->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_1 = new QGraphicsView(MainWidget);
        SkillPoint_HP_1->setObjectName(QString::fromUtf8("SkillPoint_HP_1"));
        SkillPoint_HP_1->setGeometry(QRect(325, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_1->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_1->setSizePolicy(sizePolicy1);
        SkillPoint_HP_1->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SkillPoint_HP_9 = new QGraphicsView(MainWidget);
        SkillPoint_HP_9->setObjectName(QString::fromUtf8("SkillPoint_HP_9"));
        SkillPoint_HP_9->setGeometry(QRect(445, 280, 10, 32));
        sizePolicy1.setHeightForWidth(SkillPoint_HP_9->sizePolicy().hasHeightForWidth());
        SkillPoint_HP_9->setSizePolicy(sizePolicy1);
        SkillPoint_HP_9->setMaximumSize(QSize(10, 32));
        SkillPoint_HP_9->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SkillPoint_Slot3.bmp);"));
        SelectFrame_1 = new QGraphicsView(MainWidget);
        SelectFrame_1->setObjectName(QString::fromUtf8("SelectFrame_1"));
        SelectFrame_1->setGeometry(QRect(250, 330, 64, 64));
        SelectFrame_1->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SelectFrame.png);"));
        SelectFrame_2 = new QGraphicsView(MainWidget);
        SelectFrame_2->setObjectName(QString::fromUtf8("SelectFrame_2"));
        SelectFrame_2->setGeometry(QRect(320, 330, 64, 64));
        SelectFrame_2->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SelectFrame.png);"));
        SelectFrame_3 = new QGraphicsView(MainWidget);
        SelectFrame_3->setObjectName(QString::fromUtf8("SelectFrame_3"));
        SelectFrame_3->setGeometry(QRect(390, 330, 64, 64));
        SelectFrame_3->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SelectFrame.png);"));
        SelectFrame_4 = new QGraphicsView(MainWidget);
        SelectFrame_4->setObjectName(QString::fromUtf8("SelectFrame_4"));
        SelectFrame_4->setGeometry(QRect(460, 330, 64, 64));
        SelectFrame_4->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SelectFrame.png);"));
        SelectFrame_5 = new QGraphicsView(MainWidget);
        SelectFrame_5->setObjectName(QString::fromUtf8("SelectFrame_5"));
        SelectFrame_5->setGeometry(QRect(530, 330, 64, 64));
        SelectFrame_5->setStyleSheet(QString::fromUtf8("border-image: url(:/image/CustomizeUI/SelectFrame.png);"));
        EnterWindowClass->setCentralWidget(MainWidget);
        productorUI->raise();
        mainEnterUI->raise();
        gameTittle->raise();
        gameTipBox->raise();
        newJounary_Gra->raise();
        loadGame_Gra->raise();
        exitGame_Gra->raise();
        LoadUI->raise();
        LoadSlot_1->raise();
        LoadSlot_2->raise();
        LoadSlot_3->raise();
        LoadSlot_1_Label_1->raise();
        LoadSlot_2_Label_1->raise();
        LoadSlot_3_Label_1->raise();
        LoadSlot_1_Label_2->raise();
        LoadSlot_1_Label_3->raise();
        LoadSlot_1_Label_4->raise();
        LoadSlot_1_Label_5->raise();
        LoadSlot_1_Label_6->raise();
        LoadSlot_2_Label_2->raise();
        LoadSlot_2_Label_3->raise();
        LoadSlot_2_Label_4->raise();
        LoadSlot_2_Label_5->raise();
        LoadSlot_2_Label_6->raise();
        LoadSlot_3_Label_2->raise();
        LoadSlot_3_Label_3->raise();
        LoadSlot_3_Label_4->raise();
        LoadSlot_3_Label_5->raise();
        LoadSlot_3_Label_6->raise();
        CustomizeUI->raise();
        PropertyGra_customizeSlot_1->raise();
        PropertyGra_customizeSlot_2->raise();
        PropertyGra_customizeSlot_3->raise();
        SkillPoint_TextLabel->raise();
        Bullet_CustomizeSlot_1->raise();
        Bullet_CustomizeSlot_2->raise();
        Bullet_CustomizeSlot_3->raise();
        Bullet_CustomizeSlot_4->raise();
        Bullet_CustomizeSlot_5->raise();
        CustomizeOver_Button->raise();
        Increase_button_customizeSlot_3->raise();
        Increase_button_customizeSlot_1->raise();
        Increase_button_customizeSlot_2->raise();
        Decrease_button_customizeSlot_1->raise();
        Decrease_button_customizeSlot_2->raise();
        Decrease_button_customizeSlot_3->raise();
        SkillPoint_ATK_4->raise();
        SkillPoint_ATK_9->raise();
        SkillPoint_ATK_1->raise();
        SkillPoint_ATK_6->raise();
        SkillPoint_ATK_8->raise();
        SkillPoint_ATK_5->raise();
        SkillPoint_ATK_3->raise();
        SkillPoint_ATK_10->raise();
        SkillPoint_ATK_2->raise();
        SkillPoint_ATK_7->raise();
        SkillPoint_DEF_8->raise();
        SkillPoint_DEF_9->raise();
        SkillPoint_DEF_5->raise();
        SkillPoint_DEF_10->raise();
        SkillPoint_DEF_3->raise();
        SkillPoint_DEF_1->raise();
        SkillPoint_DEF_7->raise();
        SkillPoint_DEF_6->raise();
        SkillPoint_DEF_4->raise();
        SkillPoint_DEF_2->raise();
        SkillPoint_HP_8->raise();
        SkillPoint_HP_3->raise();
        SkillPoint_HP_6->raise();
        SkillPoint_HP_10->raise();
        SkillPoint_HP_4->raise();
        SkillPoint_HP_5->raise();
        SkillPoint_HP_2->raise();
        SkillPoint_HP_7->raise();
        SkillPoint_HP_1->raise();
        SkillPoint_HP_9->raise();
        SelectFrame_1->raise();
        SelectFrame_2->raise();
        SelectFrame_3->raise();
        SelectFrame_4->raise();
        SelectFrame_5->raise();

        retranslateUi(EnterWindowClass);

        QMetaObject::connectSlotsByName(EnterWindowClass);
    } // setupUi

    void retranslateUi(QMainWindow *EnterWindowClass)
    {
        EnterWindowClass->setWindowTitle(QApplication::translate("EnterWindowClass", "EnterWindow", nullptr));
        LoadSlot_1_Label_1->setText(QApplication::translate("EnterWindowClass", "1", nullptr));
        LoadSlot_2_Label_1->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_3_Label_1->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_1_Label_2->setText(QApplication::translate("EnterWindowClass", "2", nullptr));
        LoadSlot_1_Label_3->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_1_Label_4->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_1_Label_5->setText(QApplication::translate("EnterWindowClass", "5", nullptr));
        LoadSlot_1_Label_6->setText(QApplication::translate("EnterWindowClass", "6", nullptr));
        LoadSlot_2_Label_2->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_2_Label_3->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_2_Label_4->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_2_Label_5->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_2_Label_6->setText(QApplication::translate("EnterWindowClass", "3", nullptr));
        LoadSlot_3_Label_2->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_3_Label_3->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_3_Label_4->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_3_Label_5->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        LoadSlot_3_Label_6->setText(QApplication::translate("EnterWindowClass", "4", nullptr));
        SkillPoint_TextLabel->setText(QApplication::translate("EnterWindowClass", "666", nullptr));
        CustomizeOver_Button->setText(QString());
        Increase_button_customizeSlot_3->setText(QString());
        Increase_button_customizeSlot_1->setText(QString());
        Increase_button_customizeSlot_2->setText(QString());
        Decrease_button_customizeSlot_1->setText(QString());
        Decrease_button_customizeSlot_2->setText(QString());
        Decrease_button_customizeSlot_3->setText(QString());
    } // retranslateUi

};

namespace Ui {
    class EnterWindowClass: public Ui_EnterWindowClass {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_ENTERWINDOW_H
